# Generated by Django 5.0.5 on 2024-05-14 07:03

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='posts/default.jpg', upload_to=app.models.upload_to, verbose_name='Image'),
        ),
    ]
